/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
// import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { getCookies, getCookie, setCookies, removeCookies } from "cookies-next";

export default function Home({ data }) {
	var dis = false;

	const initialState = {
		bet: "",
	};
	getCookie("sold") > Number("-5") ? null : setCookies("sold", 500);
	getCookie("sold");
	let sold;
	const [betData, setbetData] = useState(initialState);
	function setbetDatax2() {
		if (Number(sold) > Number(bet) * 2) setbetData({ bet: bet * 2 });
		else alert("Nu ai bani bobita");
	}
	const { bet } = betData;
	sold = Number(getCookie("sold"));
	

	const handleChangeInput = (e) => {
		const { name, value } = e.target;
		setbetData({ ...betData, [name]: value });
	};
	const [deck__id, setId] = useState(data.deck_id);

	const [cards, setCards] = useState([]);
	const [cardssarr, setcardsarr] = useState([]);

	const [cardsCasa, setCardsCasa] = useState([]);
	const [cardssarrCasa, setcardsarrCasa] = useState([]);

	function timeHit() {
		setTimeout(hit(), 500);
	}
	function timeHitCasa() {
		setTimeout(hitCasa(), 500);
	}
	function hit() {
		axios
			.get(`https://deckofcardsapi.com/api/deck/${deck__id}/draw/?count=1`)
			.then(function (response) {
				setCards(response.data.cards);
				// console.log(response.data.cards);
			});

		cardssarr.push(cards[0]);
		test2();
	}

	function hitCasa() {
		axios
			.get(`https://deckofcardsapi.com/api/deck/${deck__id}/draw/?count=1`)
			.then(function (response) {
				setCardsCasa(response.data.cards);
				// console.log(response.data.cards);
			});
		cardssarrCasa.push(cardsCasa[0]);
		test3();
	}

	let str = "0";

	for (let i = 1; i < cardssarr.length; i++) {
		if (
			cardssarr[i].value == "JACK" ||
			cardssarr[i].value == "QUEEN" ||
			cardssarr[i].value == "KING"
		) {
			str = Number(str) + Number(10);
		} else if (cardssarr[i].value === "ACE" && Number(str) > Number(10)) {
			str = Number(str) + Number(1);
		} else if (cardssarr[i].value === "ACE" && Number(str) < Number(10)) {
			str = Number(str) + Number(11);
		} else str = Number(str) + Number(cardssarr[i].value);
		var dis = true;
	}

	let str2 = "0";
	for (let i = 1; i < cardssarrCasa.length; i++) {
		if (
			cardssarrCasa[i].value == "JACK" ||
			cardssarrCasa[i].value == "QUEEN" ||
			cardssarrCasa[i].value == "KING"
		) {
			str2 = Number(str2) + Number(10);
		} else if (cardssarrCasa[i].value === "ACE" && Number(str2) > Number(10)) {
			str2 = Number(str2) + Number(1);
		} else if (cardssarrCasa[i].value === "ACE" && Number(str2) < Number(10)) {
			str2 = Number(str2) + Number(11);
		} else str2 = Number(str2) + Number(cardssarrCasa[i].value);
	}

	function test2() {
		if (Number(str) > Number(21)) {
			alert(`You Lost ${bet} $`);
			setcardsarr([]);
			setcardsarrCasa([]);
			let cook = Number(sold) - Number(bet);
		
			setCookies("sold", cook);
		} else if (Number(str) == Number(21)) {
			alert(`You Wom ${Number(bet*2)} $`);
			sold = sold + Number(bet);
			setcardsarr([]);
			setcardsarrCasa([]);
			let cook = Number(sold) + Number(bet);
		
			setCookies("sold", cook);
		}
	}
	function test3() {
		test2();
		if (Number(str2) > Number(21)) {
			alert(`You Won ${bet} $$`);
			setCookies("sold", cook);
			setcardsarr([]);
			setcardsarrCasa([]);
			let cook = Number(sold) + Number(bet);
		;
			setCookies("sold", cook);
		} else if (Number(str2) > Number(str)) {
			alert(`You Lost ${bet} $`);
			setcardsarr([]);
			setcardsarrCasa([]);
			let cook = Number(sold) - Number(bet);
		
		}
	}
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="p-1 border-2 rounded-xl border-rose-600 container bg-emerald-700 mx-auto mt-5 h-128">
				<div className="flex flex-row h-8">
					<div className="basis-1/3 ml-3 whitespace-nowrap font-semibold">
						Sold: {sold}$
					</div>
					<div className="mr-1 font-semibold">Bet: </div>

					<div className="mb-3 xl:w-96">
						<input
							value={bet}
							name="bet"
							onChange={handleChangeInput}
							required
							type="number"
							default="0"
							disabled={dis}
							step='50'
							className="

							
        form-control
        block
        w-full
        p-0/25
        text-base
        font-semibold
        text-red-800
        bg-white bg-clip-padding
        border border-solid border-gray-500
        rounded
        transition
        ease-in-out
        m-0 pl-1
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
      "
							id="exampleFormControlInput1"
							placeholder="Example label"
						/>
					</div>
					<div className="basis-1/4 flex grow justify-end ">
						<div className=" ml-2  item mr-2 font-semibold">
							{" "}
							Profit:{sold - 500}$
						</div>
					</div>
				</div>
				<div className="grid justify-items-center grid-cols-2 p-1 ">
					<p className=" pr-8 text-xl font-semibold text-dark-800 ">
						Player <span className="text-2xl text-blue-800">: {str} </span>
					</p>
					<p className="pr-24 text-xl font-semibold text-red-700">
						Casa <span className="text-2xl text-gray-800"> {str2} </span>
					</p>
				</div>
				<div className=" grid justify-items-center grid-cols-2 pt-3 h-[25rem] mr-16">
					<div className="w-28">
						{cardssarr.map((item, x) =>
							x > 0 ? (
								<div key={x}>
									<img
										className="imagej"
										src={`${cardssarr[x].image}`}
										alt="cartejoc"
									></img>
									<style jsx>{`
										.imagej {
											transform: translate(
												${0.7 * (x - 1)}rem,
												${-8 * (x - 1)}rem
											);
										}
									`}</style>
								</div>
							) : null
						)}
					</div>

					<div className=" w-28 ">
						{cardssarrCasa.map((item, x) =>
							x > 0 ? (
								<div key={x}>
									<img
										className="imagej"
										src={`${cardssarrCasa[x].image}`}
										alt="cartejoc"
									></img>
									<style jsx>{`
										.imagej {
											transform: translate(
												${0.7 * (x - 1)}rem,
												${-8 * (x - 1)}rem
											);
										}
									`}</style>
								</div>
							) : null
						)}
					</div>
				</div>
				<div className="grid justify-items-center grid-cols-3 p-1 ">
					<button
						onClick={setbetDatax2}
						className="w-24 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"
					>
						Double
					</button>

					<button
						onClick={timeHitCasa}
						className="w-24 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"
					>
						Stand
					</button>

					<button
						onClick={timeHit}
						className="w-24 bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"
					>
						Hit
					</button>
				</div>
				
			</div>
			<ul className='m-3'>
			<span className='pl-10'>1: lorem ipsum dolor</span><br></br>
			<span className='pl-10'>2: lorem ipsum dolor</span><br></br>
			<span className='pl-10'>3: lorem ipsum dolor</span><br></br>
			</ul>
		</div>
	);
}
export async function getServerSideProps() {
	const res = await axios.get(
		"https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1"
	);
	const data = res.data;

	return { props: { data } };
}
